# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AllCanopies',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('serial_number', models.CharField(max_length=45)),
                ('is_rentable', models.CharField(max_length=45)),
                ('manufacturer', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('date_of_manufacture', models.DateTimeField()),
                ('size', models.CharField(max_length=45)),
                ('last_repack_date', models.DateTimeField()),
                ('next_repack_date', models.DateTimeField()),
                ('jump_count', models.IntegerField()),
                ('ride_count', models.IntegerField()),
            ],
            options={
                'db_table': 'all_canopies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AllItems',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=45)),
                ('rig_number', models.IntegerField()),
                ('aad', models.IntegerField()),
                ('container', models.IntegerField()),
                ('isTandem', models.CharField(max_length=45)),
                ('canopy_on_rig', models.IntegerField()),
                ('canopy_sn', models.CharField(max_length=45)),
                ('container_sn', models.CharField(max_length=45)),
                ('aad_sn', models.CharField(max_length=45)),
                ('lifespan', models.CharField(max_length=45)),
                ('is_rentable', models.CharField(max_length=45)),
                ('manufacturer', models.CharField(max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('date_of_manufacture', models.DateTimeField()),
                ('size', models.CharField(max_length=45)),
                ('next_repack_date', models.DateTimeField()),
                ('jump_count', models.IntegerField()),
                ('ride_count', models.IntegerField()),
                ('packed_by_employee_id', models.IntegerField()),
            ],
            options={
                'db_table': 'all_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dropzones',
            fields=[
                ('dropzone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'dropzones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRoles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'employee_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('pin', models.IntegerField()),
                ('employment_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesVsSignouts',
            fields=[
                ('signout_id', models.AutoField(primary_key=True, serialize=False)),
                ('jumpmaster', models.CharField(max_length=90)),
                ('load_number', models.IntegerField()),
                ('rig_id', models.IntegerField()),
                ('packed_by', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'all_employees_vs_signouts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesVsSignoutsStudent',
            fields=[
                ('signout_id', models.AutoField(primary_key=True, serialize=False)),
                ('jumpmaster', models.CharField(max_length=90)),
                ('load_number', models.IntegerField()),
                ('rig_id', models.IntegerField()),
                ('packed_by', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'employees_vs_signouts_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesVsSignoutsTandem',
            fields=[
                ('signout_id', models.AutoField(primary_key=True, serialize=False)),
                ('jumpmaster', models.CharField(max_length=90)),
                ('load_number', models.IntegerField()),
                ('rig_id', models.IntegerField()),
                ('packed_by', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'employees_vs_signouts_tandem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(blank=True, max_length=45, null=True)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('is_rentable', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemTypes',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'item_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('renter_name', models.CharField(max_length=45)),
                ('rental_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rentals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RigsAuditTrail',
            fields=[
                ('rig_audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('rig_id', models.IntegerField()),
                ('container_id', models.IntegerField()),
                ('aad_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('date_of_change', models.DateTimeField()),
            ],
            options={
                'db_table': 'rigs_audit_trail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=12)),
                ('service_type', models.CharField(max_length=11)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Signouts',
            fields=[
                ('signout_id', models.AutoField(primary_key=True, serialize=False)),
                ('load_number', models.IntegerField()),
            ],
            options={
                'db_table': 'signouts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AutomaticActivationDevices',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Items')),
                ('deployment_timestamp', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=45)),
                ('lifespan', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'automatic_activation_devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Canopies',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Items')),
                ('serial_number', models.CharField(blank=True, max_length=45, null=True)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('date_of_manufacture', models.DateTimeField(blank=True, null=True)),
                ('jump_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canopies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Items')),
                ('serial_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'containers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesActions',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Employees')),
                ('timestamp', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Actions')),
            ],
            options={
                'db_table': 'employees_actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesEmployeeRoles',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Employees')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.EmployeeRoles')),
            ],
            options={
                'db_table': 'employees_employee_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesRentals',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Employees')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Rentals')),
            ],
            options={
                'db_table': 'employees_rentals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesServices',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Employees')),
                ('timestamp', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Actions')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Services')),
            ],
            options={
                'db_table': 'employees_services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeesSignouts',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Employees')),
                ('packed_signout', models.CharField(db_column='packed_or_signout', max_length=7)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'employees_signouts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsRentals',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Items')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Rentals')),
            ],
            options={
                'db_table': 'items_rentals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rigs',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Items')),
                ('rig_id', models.AutoField(primary_key=True, unique=True)),
                ('istandem', models.CharField(db_column='isTandem', max_length=4)),
                ('aad', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.AutomaticActivationDevices')),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Containers')),
            ],
            options={
                'db_table': 'rigs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='items',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.ItemTypes'),
        ),
        migrations.AddField(
            model_name='employees',
            name='dropzone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Dropzones'),
        ),
        migrations.CreateModel(
            name='ReserveCanopies',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dropZoneHQ.Canopies')),
                ('last_repack_date', models.DateTimeField()),
                ('next_repack_date', models.DateTimeField()),
                ('ride_count', models.IntegerField(blank=True, null=True)),
                ('packed_by_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Employees')),
            ],
            options={
                'db_table': 'reserve_canopies',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='signouts',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Rigs'),
        ),
        migrations.AddField(
            model_name='employeessignouts',
            name='signout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Signouts'),
        ),
        migrations.AddField(
            model_name='canopies',
            name='rig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Rigs'),
        ),
        migrations.AddField(
            model_name='allcanopies',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropZoneHQ.Rigs'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsrentals',
            unique_together=set([('item', 'rental')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeessignouts',
            unique_together=set([('employee', 'signout')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeesservices',
            unique_together=set([('employee', 'service')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeesrentals',
            unique_together=set([('employee', 'rental')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeesemployeeroles',
            unique_together=set([('employee', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeesactions',
            unique_together=set([('employee', 'action')]),
        ),
    ]
