# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropZoneHQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigs',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dropZoneHQ.Items'),
        ),
    ]
